kit:
  name: "Broadleaf Starter Kit"
  link: https://github.com/qubell-bazaar/broadleaf-starter-kit
  applications:
    - name: "Broadleaf"
      manifest: https://raw.github.com/qubell-bazaar/broadleaf-starter-kit/gce/broadleaf-starter-kit.yml
    - name: "Database"
      manifest: https://raw.github.com/qubell-bazaar/component-mysql-dev/gce/component-mysql-dev.yml
    - name: "Load Balancer"
      manifest: https://raw.github.com/qubell-bazaar/component-haproxy/gce/component-haproxy.yml
    - name: "Application Server"
      manifest: https://raw.github.com/qubell-bazaar/component-tomcat-dev/gce/component-tomcat-dev.yml
    - name: "Solr Cloud"
      manifest: https://raw.github.com/qubell-bazaar/component-solr-dev/gce/component-solr-dev.yml
    - name: "Zookeeper"
      manifest: https://raw.github.com/qubell-bazaar/component-zookeeper-dev/gce/component-zookeeper-dev.yml
  provider:
    name: "Qubell"
    link: http://qubell.com
  documentation:
    overview: |
      This application requires the following items to be configured in your environment:
        * Amazon EC2 or Rackspace CloudServers or GCE account;
        * Ports 80 and 8080 open on the ﬁrewall.
      Please refer to the Getting Started for step-by-step instructions on how to configure your environment.
